host: 0.0.0.0
port: 8081
name: future
log:
  level: info
  stats: true
pprof:
  enable: false
  prefix:
databases:
  default:
    driver: "mysql"
    dsn: "root:mysql_K62szr@tcp(192.168.5.23:3306)/future?charset=utf8mb4&parseTime=True&loc=Local"
